### ISSUE TITLE
[BUG]: Lag and excessive resource usage when viewing `Opt Pipeline`

### ISSUE THREAD

**Issue by tinnamchoi** [compiler-explorer/compiler-explorer#8583]
### Describe the bug

* The page is completely unresponsive for large chunks of time.
* Excessive RAM and CPU usage.

### Steps to reproduce

```cpp
#include <vector>

auto foo(std::vector<std::vector<int>> a)
{
    decltype(a){} = a;
}
```
* Compile with `x86-64 clang 22.1.0` with `-O3`
* Open `Opt Pipeline Viewer`

Note: You might get `Compilation failed: Request failed: gateway timeout` and need to recompile a few times.

### Expected behavior

Not nearly as much lag or resource usage.
Don't know if this is a bug in CE, Clang, or if it's just normal behaviour, but it should not freeze and/or there should be safeguards against such levels of resource usage regardless.

### Reproduction link

https://godbolt.org/z/xznhvG6h8

### Screenshots

<img width="664" height="68" alt="Image" src="https://github.com/user-attachments/assets/7077f64d-50ba-4f26-b466-d541774077eb" />

<img width="714" height="121" alt="Image" src="https://github.com/user-attachments/assets/c4ab2e8d-ef7d-48d9-948b-05189de97e70" />

### Operating System

Arch Linux x86_64

### Browser version

Firefox 148.0

**Comment by OfekShilon** [comment]
Compilation passes within timeout limits with `-O1` instead of `-O3`, and this is the measured timing breakdown:

<img width="396" height="454" alt="Image" src="https://github.com/user-attachments/assets/228d1dda-80f4-4dec-ab3d-fe570fe31e59" />

So it's not entirely clang. This might be actionable.

**Comment by OfekShilon** [comment]
Remarkably, it seems the main culprit is name demangling. If you check off `options/demangle symbols` you get timing like: 

<img width="392" height="430" alt="Image" src="https://github.com/user-attachments/assets/2ce7fdd8-b82f-4bf8-bfe2-596b6be21b75" />

**Comment by OfekShilon** [comment]
I implemented some optimizations for this flow in https://github.com/compiler-explorer/compiler-explorer/pull/8869. I'm not closing this yet, will revisit after the next deployment - if it's not enough we can do more.

**Comment by OfekShilon** [comment]
It seems the 1st attempt wasn't enough, here's another one: https://github.com/compiler-explorer/compiler-explorer/pull/8876

I'll recheck this after the near deploy.

**Comment by OfekShilon** [comment]
After the 2nd optimizations round things are looking better:

<img width="299" height="325" alt="Image" src="https://github.com/user-attachments/assets/59fea197-9e67-45ed-bc91-3de7bfb9643e" />

The compilation time now dominates the overall time. @tinnamchoi I'm closing this - if you come across other problematic examples please share them. And thanks for raising this!
