### ISSUE TITLE
[BUG]: -fno-omit-frame-pointer is ignored for GCC

### ISSUE THREAD

**Issue by ilyakurdyukov** [compiler-explorer/compiler-explorer#3674]
### Describe the bug

This code (from `libyuv/source/row_gcc.cc`) won't compile with my local GCC if I add the -fno-omit-frame-pointer option. But in Compiler Explorer, adding this option makes no difference.

```c
#include <stdint.h>

typedef uint8_t uvec8[16];

// Shuffle table for converting RGB to Planar.
static const uvec8 kShuffleMaskRToRGB0 = {0u, 128u, 128u, 1u, 128u, 128u,
                                          2u, 128u, 128u, 3u, 128u, 128u,
                                          4u, 128u, 128u, 5u};
static const uvec8 kShuffleMaskGToRGB0 = {128u, 0u, 128u, 128u, 1u, 128u,
                                          128u, 2u, 128u, 128u, 3u, 128u,
                                          128u, 4u, 128u, 128u};
static const uvec8 kShuffleMaskBToRGB0 = {128u, 128u, 0u, 128u, 128u, 1u,
                                          128u, 128u, 2u, 128u, 128u, 3u,
                                          128u, 128u, 4u, 128u};

static const uvec8 kShuffleMaskGToRGB1 = {5u, 128u, 128u, 6u, 128u, 128u,
                                          7u, 128u, 128u, 8u, 128u, 128u,
                                          9u, 128u, 128u, 10u};
static const uvec8 kShuffleMaskBToRGB1 = {128u, 5u, 128u, 128u, 6u, 128u,
                                          128u, 7u, 128u, 128u, 8u, 128u,
                                          128u, 9u, 128u, 128u};
static const uvec8 kShuffleMaskRToRGB1 = {128u, 128u, 6u,  128u, 128u, 7u,
                                          128u, 128u, 8u,  128u, 128u, 9u,
                                          128u, 128u, 10u, 128u};

static const uvec8 kShuffleMaskBToRGB2 = {10u, 128u, 128u, 11u, 128u, 128u,
                                          12u, 128u, 128u, 13u, 128u, 128u,
                                          14u, 128u, 128u, 15u};
static const uvec8 kShuffleMaskRToRGB2 = {128u, 11u, 128u, 128u, 12u, 128u,
                                          128u, 13u, 128u, 128u, 14u, 128u,
                                          128u, 15u, 128u, 128u};
static const uvec8 kShuffleMaskGToRGB2 = {128u, 128u, 11u, 128u, 128u, 12u,
                                          128u, 128u, 13u, 128u, 128u, 14u,
                                          128u, 128u, 15u, 128u};

void MergeRGBRow_SSSE3(const uint8_t* src_r,
                       const uint8_t* src_g,
                       const uint8_t* src_b,
                       uint8_t* dst_rgb,
                       int width) {
  asm volatile(

      //LABELALIGN
      "1:                                        \n"
      "movdqu     (%0),%%xmm0                    \n"
      "movdqu     (%1),%%xmm1                    \n"
      "movdqu     (%2),%%xmm2                    \n"
      "pshufb     %5, %%xmm0                     \n"
      "pshufb     %6, %%xmm1                     \n"
      "pshufb     %7, %%xmm2                     \n"
      "por        %%xmm1,%%xmm0                  \n"
      "por        %%xmm2,%%xmm0                  \n"
      "movdqu     %%xmm0,(%3)                    \n"

      "movdqu     (%0),%%xmm0                    \n"
      "movdqu     (%1),%%xmm1                    \n"
      "movdqu     (%2),%%xmm2                    \n"
      "pshufb     %8, %%xmm0                     \n"
      "pshufb     %9, %%xmm1                     \n"
      "pshufb     %10, %%xmm2                    \n"
      "por        %%xmm1,%%xmm0                  \n"
      "por        %%xmm2,%%xmm0                  \n"
      "movdqu     %%xmm0,16(%3)                  \n"

      "movdqu     (%0),%%xmm0                    \n"
      "movdqu     (%1),%%xmm1                    \n"
      "movdqu     (%2),%%xmm2                    \n"
      "pshufb     %11, %%xmm0                    \n"
      "pshufb     %12, %%xmm1                    \n"
      "pshufb     %13, %%xmm2                    \n"
      "por        %%xmm1,%%xmm0                  \n"
      "por        %%xmm2,%%xmm0                  \n"
      "movdqu     %%xmm0,32(%3)                  \n"

      "lea        0x10(%0),%0                    \n"
      "lea        0x10(%1),%1                    \n"
      "lea        0x10(%2),%2                    \n"
      "lea        0x30(%3),%3                    \n"
      "sub        $0x10,%4                       \n"
      "jg         1b                             \n"
      : "+r"(src_r),               // %0
        "+r"(src_g),               // %1
        "+r"(src_b),               // %2
        "+r"(dst_rgb),             // %3
        "+r"(width)                // %4
      : "m"(kShuffleMaskRToRGB0),  // %5
        "m"(kShuffleMaskGToRGB0),  // %6
        "m"(kShuffleMaskBToRGB0),  // %7
        "m"(kShuffleMaskRToRGB1),  // %8
        "m"(kShuffleMaskGToRGB1),  // %9
        "m"(kShuffleMaskBToRGB1),  // %10
        "m"(kShuffleMaskRToRGB2),  // %11
        "m"(kShuffleMaskGToRGB2),  // %12
        "m"(kShuffleMaskBToRGB2)   // %13
      : "memory", "cc", "xmm0", "xmm1", "xmm2");
}
```

### Steps to reproduce

Compile with GCC 11.2 from Ubuntu 22.04 with -O2 -mcmodel=large -fno-omit-frame-pointer and try the same in Compiler Explorer.

### Expected behavior

Compilation should fail with the error:

```
test.cpp: In function ‘void MergeRGBRow_SSSE3(const uint8_t*, const uint8_t*, const uint8_t*, uint8_t*, int)’:
test.cpp:41:3: error: ‘asm’ operand has impossible constraints
   41 |   asm volatile(
      |   ^~~
```

### Reproduction link

https://godbolt.org/z/ThMsT3db8

### Screenshots

Not applicable

### Operating System

Ubuntu 22.04

**Comment by ilyakurdyukov** [comment]
Now I can see that the code is different, with and without this option, but real GCC prints this error, Compiler Explorer doesn't.

**Comment by mattgodbolt** [comment]
That's very unusual. We build our GCC locally and the source to the build etc is in the compiler-explorer/gcc-builder repository. There's nothing specific we do to change compilation in that way. Does Ubuntu add in extra patches?

**Comment by ilyakurdyukov** [comment]
Added -fpic ("-O2 -mcmodel=large -fno-omit-frame-pointer -fpic") and the error is reproduced as in Ubuntu.

So Compiler Explorer uses GCC which defaults to -fno-pic, but on Ubuntu the default is -fpic?

**Comment by dkm** [comment]
Is it possible that you are building to a binary on ubuntu ? It does (as most distro now) default to PIE

**Comment by dkm** [comment]
Adding `-fno-pie` "fixes" the issue on ubuntu, so that confirms this is caused by the different default for PIE between vanilla GCC and Ubuntu's.

Does that sound correct ?

**Comment by partouf** [comment]
Also adding `-fpie` or `-fPIE` reproduces it in CE.

**Comment by ilyakurdyukov** [comment]
Yes, that's because the difference in -fpie/-fno-pie mode between GCC in Ubuntu and in CE.

**Comment by dkm** [comment]
Great :) So I'll close this issue, but feel free to reopen (or create a new one ) :)

**Comment by ilyakurdyukov** [comment]
> Great :) So I'll close this issue, but feel free to reopen (or create a new one ) :)

Maybe change the default GCC configuration in Compile Explorer to -fpie if many (need research) Linux distributions use GCC with -fpie by default?
