### ISSUE TITLE
[REQUEST]: Investigate utf8 issues with output: "Unknown code"

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/compiler-explorer#3435]
### Is your feature request related to a problem? Please describe

https://twitter.com/Cor3ntin/status/1502357281186402310?s=20&t=L1CnMe8pwqgIUOVetbIncA

https://godbolt.org/z/E6bbshGvv

getting bad unicode things in the output:

```
<source>:1:9: error: macro name must be an identifier
#define Unknown code<U+1F984> &
        ^
<source>:2:5: error: unexpected character <U+1F984>
int Unknown code<U+1F984>;
    ^~~~~~~~~
<source>:2:1: warning: declaration does not declare anything [-Wmissing-declarations]
int Unknown code<U+1F984>;
```

### Describe the solution you'd like

Unsure, but it seems confusing.

### Describe alternatives you've considered

na

### Additional context

Not applicable

**Comment by partouf** [comment]
From an old example from 2017 we get this https://gcc.godbolt.org/z/bvjarsf5f
Which doesn't work either in clang trunk

It does work in Clang 13.0.1 as well

So trunk is either different somehow or broken

**Comment by cor3ntin** [comment]
@partouf this particular example fails in very old clang https://godbolt.org/z/eGhY4Tqb4  - but most importantly the output you get in a terminal is different

```foo.cpp:1:9: error: macro name must be an identifier
#define <U+1F984> &
        ^
foo.cpp:2:5: error: unexpected character <U+1F984>
int <U+1F984>;
    ^~~~~~~~~
foo.cpp:2:1: warning: declaration does not declare anything [-Wmissing-declarations]
int <U+1F984>;
^~~
1 warning and 2 errors generated.```

The difference is that "Unknown code" is injected in the diagnostic message somehow - 
I'm not confident at all it comes from CE but it certainly doesn't come from GCC

**Comment by partouf** [comment]
```
#define [0m[7m<U+1F984>[0m &
```

https://www.csie.ntu.edu.tw/~r92094/c++/VT100.html

[7m is... "reverse video"... I guess it's supposed to swap default background and text color

**Comment by partouf** [comment]
I don't think we can "actually" implement that (other than just assuming it's black/white), perhaps we should just add `} else if (code === 7) { return '';` here https://github.com/compiler-explorer/compiler-explorer/blob/main/static/ansi-to-html.ts#L170

**Comment by cor3ntin** [comment]
> I don't think we can "actually" implement that (other than just assuming it's black/white), perhaps we should just add `} else if (code === 7) { return '';` here https://github.com/compiler-explorer/compiler-explorer/blob/main/static/ansi-to-html.ts#L170

I think that would make a lot of sense!
