### ISSUE TITLE
[COMPILER REQUEST]: Upgrade flang-trunk (flang-new) to trunk.

### ISSUE THREAD

**Issue by AshokBhat** [compiler-explorer/compiler-explorer#4334]
### Compiler name

LLVM flang

### Compiler version

Trunk

### Compiler language

Fortran

### Compiler homepage

https://github.com/llvm/llvm-project/tree/main/flang

### Motivation

Compiler Explorer has 15.0 rc1 version. Having trunk version helps real users to determine whether their code can be compiled by LLVM flang trunk version. Since the compiler says it is trunk, it can mislead users on what latest flang is capable of.

**Comment by DavidSpickett** [comment]
flang-trunk should be tracking llvm-project's `main` as far as I can tell, but it has been failing to build for months (though not long enough to still be a 15.x, but that's not important for now).

https://github.com/compiler-explorer/clang-builder/blob/9f785857b49285a88eeb2a96c03952b9e219d6a4/build/build.sh#L81

Going from the status page here https://compiler-explorer.github.io/compiler-workflows/build-status the latest build was https://github.com/compiler-explorer/compiler-workflows/actions/runs/6937431767/job/18871474132.

Downloading the logs I see:
```
2023-11-21T00:33:42.1239679Z                  from /root/llvm-project/flang/lib/Parser/io-parsers.cpp:11:
2023-11-21T00:33:42.1241962Z /root/llvm-project/flang/include/flang/Common/enum-class.h: In static member function 'static std::string_view Fortran::parser::DefinedOperator::EnumToString(Fortran::parser::DefinedOperator::IntrinsicOperator)':
2023-11-21T00:33:42.1244738Z /root/llvm-project/flang/include/flang/Parser/parse-tree.h:600:3:   in 'constexpr' expansion of 'Fortran::common::EnumNames<17>(((const char*)(& vaArgs)))'
2023-11-21T00:33:42.1247886Z /root/llvm-project/flang/include/flang/Common/enum-class.h:51:16: error: '(((const char*)(& vaArgs)) == 0)' is not a constant expression
2023-11-21T00:33:42.1249133Z    51 |     } else if (!start) {
2023-11-21T00:33:42.1249613Z       |                ^~~~~~
```
And similar messages.

This comes from https://github.com/llvm/llvm-project/blob/main/flang/include/flang/Common/enum-class.h.

The compiler being used here is gcc 9.2.0. I have tested 9.4.0 and it works, and we (Linaro) have a GCC bot building with 13.something which is also fine. Never seen this problem with clang.

I don't know the standard-ese here but at a glance the expression seems fine in this context. Given that it works in 9.4.0 I'm inclined to say it was a bug that was fixed.

Am building a 9.2.0 locally to see if there's an easy workaround. If not then perhaps we can switch to an alternative compiler, or update the gcc version in the build image. Though I am not sure where that builder image comes from.

**Comment by DavidSpickett** [comment]
This can be closed, we now have flang-new built from `main` again:
```
flang-new version 18.0.0git (https://github.com/llvm/llvm-project.git b7355ee99ec63f44a6dc4f7dad9bb5a130bcc0eb)
```

**Comment by mattgodbolt** [comment]
Thanks @DavidSpickett !
