### PR TITLE
Rust library support

### PR DESCRIPTION
**Pull request by partouf**
Todo:
* [x] Add more libraries
* [x] Try not to override `downloadAndExtractPackage()`
* [ ] More flags to support? (it appears `edition` is not that relevant after all, but maybe there are still others)

### CODE REVIEW

File: lib/compilers/rust.ts [hunk 1]
```diff
@@ -52,11 +55,54 @@ export class RustCompiler extends BaseCompiler {
...
+
+    override getIncludeArguments(libraries) {
+        const includeFlag = '--extern';
+        return _.flatten(
+            _.map(libraries, selectedLib => {
+                const foundVersion = this.findLibVersion(selectedLib);
+                if (!foundVersion) return false;
+                const list: string[] = [];
+                for (const rlib of foundVersion.path) {
+                    list.push(includeFlag, `${foundVersion.name}=${foundVersion.name}/build/debug/${rlib}`);
```
Comment (partouf) [inline lib/compilers/rust.ts:74]: Having this path preformatted probably takes away the possibility of local users being able to add libraries, is that something we should account for?

File: lib/compilers/rust.ts [hunk 2]
```diff
@@ -52,11 +55,54 @@ export class RustCompiler extends BaseCompiler {
...
+        libLinks,
+        userOptions,
+        staticLibLinks,
+    ) {
+        return options.concat(userOptions, libIncludes, libOptions, libPaths, libLinks, staticLibLinks, [
+            this.filename(inputFilename),
+        ]);
+    }
+
+    override async setupBuildEnvironment(key, dirPath): Promise<BuildEnvDownloadInfo[]> {
```
Comment (partouf) [inline lib/compilers/rust.ts:96]: Override of the setupBuildEnvironment option, because the original checks for binary/execution mode and for Rust we Always need to download the libraries

**Comment by partouf** [comment]
Currently `extern crate [libname];` is not supported. I'm not sure we can combine it with --extern

**Comment by partouf** [comment]
https://github.com/compiler-explorer/compiler-explorer/issues/2523

* [x] Generally, it would be great to have the top 100 crates (https://github.com/compiler-explorer/compiler-explorer/issues/754)
* simd (https://github.com/compiler-explorer/compiler-explorer/issues/1068)  - This no longer works with modern rust versions
* [x] itertools (https://github.com/compiler-explorer/compiler-explorer/issues/1326)
* [x] num, packed_simd and ndarray (https://github.com/compiler-explorer/compiler-explorer/issues/1731) - packed_simd is too old
* [x] itoa (https://github.com/compiler-explorer/compiler-explorer/issues/1904)
* [x] bytes (https://github.com/compiler-explorer/compiler-explorer/issues/1925)
* [x] clap (https://github.com/compiler-explorer/compiler-explorer/issues/1972)
* [x] wide and generic_array (https://github.com/compiler-explorer/compiler-explorer/issues/2172)
* [x] contracts and rand (https://github.com/compiler-explorer/compiler-explorer/issues/2515)
* [x] num_traits (https://github.com/compiler-explorer/compiler-explorer/issues/2522)
* [x] fnv (https://github.com/compiler-explorer/compiler-explorer/issues/2702)
* [x] futures (https://github.com/compiler-explorer/compiler-explorer/issues/2823)
* windows (https://github.com/compiler-explorer/compiler-explorer/issues/3241) - We don't run Rust on Windows, 
* [x] tokio (https://github.com/compiler-explorer/compiler-explorer/issues/3273)

File: lib/buildenvsetup/ceconan-rust.ts [hunk 3]
```diff
@@ -0,0 +1,130 @@
...
+        return new Promise(resolve => {
+            const startTime = process.hrtime.bigint();
+            const extract = tar.extract();
+            const gunzip = zlib.createGunzip();
+
+            extract.on('entry', async (header, stream, next) => {
+                const filename = header.name;
+                const filepath = path.join(downloadPath, filename);
+                await mkdirp(path.dirname(filepath));
+                const filestream = fs.createWriteStream(filepath);
```
[the remark this answers is not in the document]
Comment (partouf) [reply lib/buildenvsetup/ceconan-rust.ts]: fixed

**Comment by partouf** [comment]
this is now live

**Comment by jgouly** [comment]
Is there something special you have to do? `use rand;` fails to compile on godbolt.org " unresolved import `rand`"

**Comment by partouf** [comment]
> Is there something special you have to do? `use rand;` fails to compile on godbolt.org " unresolved import `rand`"

depends

rand is a little tricky, it's only available at the moment for rust 1.58-1.62 because of some build issues

**Comment by jgouly** [comment]
I can't get it to work on 1.58 to 1.62 either.

**Comment by partouf** [comment]
https://godbolt.org/z/ar3Yh9znf

**Comment by jgouly** [comment]
Ah, extern crate is needed, thanks!

**Comment by masklinn** [comment]
Maybe the "libraries" popup could provide that information? It's quite non-obvious since it has not been required for a few editions in Rust itself.

Also it looks like the crates may not have been rebuilt for 1.67? I tried using `itertools`, it works fine using the 1.66 compiler, but not 1.67.
