### ISSUE TITLE
Compiling anything with clang 3.1-3.3 which includes std headers fails.

### ISSUE THREAD

**Issue by domdom** [compiler-explorer/compiler-explorer#1461]
I am not able to compile using clang 3.1.
Consider the following code:
```cpp
#include <vector>
```
This fails to compile with the following error:
```
In file included from <source>:1:
In file included from /usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/vector:59:
/usr/lib/gcc/x86_64-linux-gnu/7.4.0/../../../../include/c++/7.4.0/bits/stl_algobase.h:59:10: fatal error: 'bits/c++config.h' file not found
#include <bits/c++config.h>
         ^
1 error generated.
Compiler returned: 1
```

**Comment by apmorton** [comment]
Just a note - this looks identical to the errors I was seeing with nearly all the compilers under nsjail when they didn't have access to /use/include.

ICC also got these errors without access to /use/bin/gcc, because it steals configuration from gcc by parsing output of running it.

**Comment by apmorton** [comment]
closing as dup of #1557
