### PR TITLE
Update Pattern Matching to P2688.

### PR DESCRIPTION
**Pull request by mpark**
Depends on
  - https://github.com/compiler-explorer/clang-builder/pull/73
  - https://github.com/compiler-explorer/infra/pull/1411

This is experimental work on an implementation for [P2688](https://wg21.link/p2688).
It implements most of the parsing and constant evaluation logic.

The following is a sample of its current capabilities:

```rust
enum Color { Red, Blue };

struct S {
  Color color;
  int xs[2];
};

struct Result {
  Color color;
  int i;
  constexpr bool operator==(const Result&) const noexcept = default;
};

constexpr auto test_nested_decomposition_pattern(const S& s) {
  return s match -> Result {
    [let c, [0, 0]] => {c, -1};
    [let c, [let x, 0]] => {c, x * 2};
    [let c, [0, let y]] => {c, y * 4};
    let [c, [x, y]] => {c, x * y};
  };
}

static_assert(test_nested_decomposition_pattern({Red, {0, 0}}) == Result{Red, -1});
static_assert(test_nested_decomposition_pattern({Red, {0, 0}}) == Result{Red, -1});
static_assert(test_nested_decomposition_pattern({Red, {0, 0}}) != Result{Red, 0});
static_assert(test_nested_decomposition_pattern({Red, {1, 0}}) == Result{Red, 2});
static_assert(test_nested_decomposition_pattern({Red, {1, 0}}) != Result{Red, 3});
static_assert(test_nested_decomposition_pattern({Red, {2, 0}}) == Result{Red, 4});
static_assert(test_nested_decomposition_pattern({Blue, {0, 1}}) == Result{Blue, 4});
static_assert(test_nested_decomposition_pattern({Blue, {0, 2}}) == Result{Blue, 8});
static_assert(test_nested_decomposition_pattern({Blue, {2, 3}}) == Result{Blue, 6});
static_assert(test_nested_decomposition_pattern({Blue, {3, 4}}) == Result{Blue, 12});
```

### CODE REVIEW

**Comment by bcardosolopes** [comment]
Awesome, I suggest you rewrite the other one (under my github username) into this, so we have a unified place for patmat.

**Comment by mattgodbolt** [comment]
We tried building:

```
024-09-17T01:55:38.4009280Z    74 |   PointerAuthenticationMode SelectedAuthenticationMode : 2;
2024-09-17T01:55:38.4009883Z       |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
2024-09-17T01:55:38.4011589Z /root/llvm-project/clang/include/clang/Basic/PointerAuthOptions.h:75:18: warning: 'clang::PointerAuthSchema::DiscriminationKind' is too small to hold all values of 'enum class clang::PointerAuthSchema::Discrimination'
2024-09-17T01:55:38.4013075Z    75 |   Discrimination DiscriminationKind : 2;
2024-09-17T01:55:38.4013546Z       |                  ^~~~~~~~~~~~~~~~~~
2024-09-17T01:55:38.4014224Z In file included from /root/llvm-project/clang/lib/AST/ByteCode/Interp.cpp:9:
2024-09-17T01:55:38.4016448Z /root/llvm-project/clang/lib/AST/ByteCode/Interp.h: In instantiation of 'bool clang::interp::CastFloatingIntegral(clang::interp::InterpState&, clang::interp::CodePtr, uint32_t) [with clang::interp::PrimType Name = clang::interp::PT_Bool; T = clang::interp::Boolean; uint32_t = unsigned int]':
2024-09-17T01:55:38.4018497Z /root/build/tools/clang/lib/AST/Opcodes.inc:6431:49:   required from here
2024-09-17T01:55:38.4019724Z /root/llvm-project/clang/lib/AST/ByteCode/Interp.h:2182:51: warning: parameter 'OpPC' set but not used [-Wunused-but-set-parameter]
2024-09-17T01:55:38.4021083Z  2182 | bool CastFloatingIntegral(InterpState &S, CodePtr OpPC, uint32_t FPOI) {
2024-09-17T01:55:38.4021794Z       |                                           ~~~~~~~~^~~~
2024-09-17T01:55:38.4029502Z /root/llvm-project/clang/lib/AST/ByteCode/Interp.h:2182:66: warning: parameter 'FPOI' set but not used [-Wunused-but-set-parameter]
2024-09-17T01:55:38.4031047Z  2182 | bool CastFloatingIntegral(InterpState &S, CodePtr OpPC, uint32_t FPOI) {
2024-09-17T01:55:38.4031737Z       |                                                         ~~~~~~~~~^~~~
2024-09-17T01:55:38.4033672Z /root/llvm-project/clang/lib/AST/ByteCode/Interp.h: In instantiation of 'bool clang::interp::Divc(clang::interp::InterpState&, clang::interp::CodePtr) [with clang::interp::PrimType Name = clang::interp::PT_Float; T = clang::interp::Floating]':
2024-09-17T01:55:38.4035664Z /root/build/tools/clang/lib/AST/Opcodes.inc:9764:30:   required from here
2024-09-17T01:55:38.4037012Z /root/llvm-project/clang/lib/AST/ByteCode/Interp.h:504:42: warning: parameter 'OpPC' set but not used [-Wunused-but-set-parameter]
2024-09-17T01:55:38.4038093Z   504 | inline bool Divc(InterpState &S, CodePtr OpPC) {
2024-09-17T01:55:38.4038629Z       |                                  ~~~~~~~~^~~~
2024-09-17T01:56:19.6348867Z [3695/5142] Building CXX object lib/Target/AMDGPU/Disassembler/CMakeFiles/LLVMAMDGPUDisassembler.dir/AMDGPUDisassembler.cpp.o
```

**Comment by mattgodbolt** [comment]
https://github.com/compiler-explorer/compiler-workflows/actions/runs/10895036067/job/30232676812 - happy to accept PRs to try and fix this but we don't otherwise have many ideas on how to fix these kinds of things.

**Comment by mpark** [comment]
Hi @mattgodbolt! I looked at the build logs and I see:
```
  /root/llvm-project/clang/lib/AST/ExprCXX.cpp:1976:73:   required from here
  /opt/compiler-explorer/gcc-9.2.0/include/c++/9.2.0/bits/stl_construct.h:75:13: error: invalid static_cast from type 'const clang::MatchCase*' to type 'void*'
     75 |     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
        |             ^~~~~~~~~~~~~~~~~~~~~~~
```
It does seem to be from my changes. I'm not quite sure why I'm not running into the same build error locally (probably building with a different stdlib or something), but I'll get it fixed!

**Comment by mattgodbolt** [comment]
Hi @mpark ! We use a docker build (with some [instructions](https://github.com/compiler-explorer/clang-builder/blob/main/README.md)) so that you can repro locally with our exact setup. Do we need to be building the compiler with a specific "main" compiler? By default we build with GCC 9.2.0 but that can be overridden in the `build.sh`

**Comment by mpark** [comment]
I just pushed https://github.com/mpark/llvm-project/commit/3b9d15a357460dd38aeddf20d2b8a18ac98c2a33 which should fix this issue!

> We use a docker build (with some [instructions](https://github.com/compiler-explorer/clang-builder/blob/main/README.md)) so that you can repro locally with our exact setup.

Oh, great. I'll take a look at this.

> Do we need to be building the compiler with a specific "main" compiler?

No, whatever the default is should be good.

> By default we build with GCC 9.2.0 but that can be overridden in the build.sh
Good to know!

**Comment by mattgodbolt** [comment]
Latest build now failing with:
```
2024-09-17T03:36:02.8059765Z -- LLVM default target triple: x86_64-unknown-linux-gnu
2024-09-17T03:36:02.8177495Z CMake Error at /root/llvm-project/libcxxabi/CMakeLists.txt:52 (message):
2024-09-17T03:36:02.8178247Z -- Configuring incomplete, errors occurred!
2024-09-17T03:36:02.8178922Z   LIBCXXABI_USE_LLVM_UNWINDER is set to ON, but libunwind is not specified in
2024-09-17T03:36:02.8179539Z   LLVM_ENABLE_RUNTIMES.
```

**Comment by mpark** [comment]
Just saw that... 🤔 I'm not sure about that one

**Comment by mattgodbolt** [comment]
I'll add `libunwind` and try again

**Comment by mpark** [comment]
Oh, I see other builds have:
```
    LLVM_ENABLE_RUNTIMES+=";libunwind"
```

**Comment by mattgodbolt** [comment]
Yup! just added and we'll giv eit anothe go!

**Comment by mattgodbolt** [comment]
Building: https://github.com/compiler-explorer/compiler-workflows/actions/runs/10895036067

**Comment by mattgodbolt** [comment]
Built now!

**Comment by mattgodbolt** [comment]
Installing now and then will look to merge

**Comment by mpark** [comment]
By the way, is there a way to load a default sample code associated with a compiler? I seem to recall something like that but not sure

**Comment by mattgodbolt** [comment]
```
$ /opt/compiler-explorer/clang-patmat-trunk/bin/clang++ --version
clang version 20.0.0git (https://github.com/mpark/llvm-project 3b9d15a357460dd38aeddf20d2b8a18ac98c2a33)
```
LGTM! merging :) thank you!

**Review by mattgodbolt — APPROVED** [review]

**Comment by mattgodbolt** [comment]
Just tested in staging and looks good: pushing to prod now. Live in ~20m
